robot_6_joint:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  
  joint1_position_controller:
    type: effort_controller/JointPositionController
    joint: base_leg1_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  joint2_position_controller:
    type: effort_controller/JointPositionController
    joint: base_leg2_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  joint3_position_controller:
    type: effort_controller/JointPositionController
    joint: base_leg3_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  joint4_position_controller:
    type: effort_controller/JointPositionController
    joint: leg1_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  joint5_position_controller:
    type: effort_controller/JointPositionController
    joint: leg2_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  joint6_position_controller:
    type: effort_controller/JointPositionController
    joint: leg3_joint
    pid: {p: 0.8 , i: 0.0 , d: 0.2}
  
  