robot_6_joint:
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 60

  
  joint1_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_leg1_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  joint2_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_leg2_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  joint3_position_controller:
    type: effort_controllers/JointPositionController
    joint: base_leg3_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  joint4_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg1_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  joint5_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg2_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  joint6_position_controller:
    type: effort_controllers/JointPositionController
    joint: leg3_joint
    pid: {p: 150 , i: 0.0 , d: 1.0}
  
  